# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('p', models.CharField(max_length=150, verbose_name='Параграф под заголовком')),
                ('offer_1', models.CharField(max_length=300, verbose_name='Предложение(под-заголовок)')),
                ('action_1_1', models.CharField(max_length=350, verbose_name='Действие для выполнение')),
                ('action_1_2', models.CharField(max_length=350, verbose_name='Действия для выполнения')),
                ('action_1_3', models.CharField(max_length=350, verbose_name='Действия для выполнения')),
                ('action_1_4', models.CharField(max_length=350, verbose_name='Действия для выполнения')),
                ('offer_2', models.CharField(max_length=300, verbose_name='Предложение(под-заголовок)')),
                ('action_2_1', models.CharField(max_length=350, verbose_name='Действие для выполнение')),
                ('action_2_2', models.CharField(max_length=350, verbose_name='Действия для выполнения')),
                ('action_2_3', models.CharField(max_length=350, verbose_name='Действия для выполнения')),
                ('action_2_4', models.CharField(max_length=350, verbose_name='Действия для выполнения')),
            ],
            options={
                'verbose_name': 'Стартовая программа',
                'verbose_name_plural': 'Стартовые программы',
            },
        ),
    ]
