# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='uploads/program/', verbose_name='Изображение программы')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('p', models.CharField(blank=True, max_length=150, null=True, verbose_name='Параграф под заголовком')),
                ('offer_1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение(под-заголовок)')),
                ('action_1_1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение')),
                ('action_1_2', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения')),
                ('action_1_3', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения')),
                ('action_1_4', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения')),
                ('offer_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение(под-заголовок)')),
                ('action_2_1', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение')),
                ('action_2_2', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения')),
                ('action_2_3', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения')),
                ('action_2_4', models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения')),
            ],
            options={
                'verbose_name': 'Стартовая программа',
                'verbose_name_plural': 'Стартовые программы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_1', models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд')),
                ('slide_2', models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд')),
                ('slide_3', models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд')),
                ('slide_4', models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд')),
                ('slide_5', models.FileField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
