# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='action_2_5',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие 2 для выполнение'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_2_6',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 2 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_2_7',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 2 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_2_8',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 2 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие 3 для выполнение'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 3 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 3 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 3 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_5',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие 3 для выполнение'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_6',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 3 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_7',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 3 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_8',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 3 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие 4 для выполнение'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 4 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 4 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 4 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_5',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие 4 для выполнение'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_6',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 4 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_7',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 4 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_8',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 4 для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='offer_3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение 3 (под-заголовок)'),
        ),
        migrations.AddField(
            model_name='program',
            name='offer_4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение 4 (под-заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие 1 для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 1 для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 1 для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 1 для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие 2 для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 2 для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 2 для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия 2 для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение 1 (под-заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение 2 (под-заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='p',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Параграф под главным заголовком'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Главный заголовок'),
        ),
    ]
