# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='action_1_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действия для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение(под-заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Предложение(под-заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='p',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Параграф под заголовком'),
        ),
    ]
