# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170409_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/program/', verbose_name='Изображение программы'),
        ),
    ]
