# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_program_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
