# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_program_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
