# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='img',
            new_name='slide_1',
        ),
        migrations.RemoveField(
            model_name='program',
            name='published',
        ),
        migrations.AddField(
            model_name='slider',
            name='slide_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='slider',
            name='slide_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='slider',
            name='slide_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
        migrations.AddField(
            model_name='slider',
            name='slide_5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/slider/', verbose_name='Слайд'),
        ),
    ]
