# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('empty_middle_name', models.BooleanField(default=False, verbose_name='Нет отчества.')),
                ('birthday', models.DateTimeField(verbose_name='День рождения')),
                ('citizenship', models.BooleanField(default=False, verbose_name='Не гражданин РФ.')),
                ('passport_data', models.CharField(max_length=26, verbose_name='Серия и номер паспорта')),
                ('phone_number', models.CharField(max_length=26, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('num_home', models.CharField(max_length=5, verbose_name='Дом')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='Квартира')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер консультанта')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Зарегистрированный', 'Зарегистрированный'), ('Пустой', 'Пустой')], default='Новый', max_length=18, verbose_name='Статус регистрации')),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Консультант',
                'verbose_name_plural': 'Консультанты',
                'ordering': ['-registered_date'],
            },
        ),
    ]
