# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Зарегистрированный А', 'Зарегистрированный А'), ('Зарегистрированный Б', 'Зарегистрированный Б'), ('Пустой', 'Пустой')], default='Новый', max_length=20, verbose_name='Статус регистрации'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='Не гражданин РФ'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='Не гражданин РФ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='Не гражданин РФ'),
        ),
    ]
