# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер консультанта')),
                ('url_to_personal_room', models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка в личный кабинет')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Зарегистрированный', 'Зарегистрированный'), ('Пустой', 'Пустой')], default='Новый', max_length=18, verbose_name='Статус регистрации')),
                ('refferal_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Реферальная ссылка')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('empty_middle_name', models.BooleanField(default=False, verbose_name='Нет отчества.')),
                ('birthday', models.DateTimeField(verbose_name='День рождения')),
                ('citizenship', models.BooleanField(default=False, verbose_name='Не гражданин РФ.')),
                ('passport_data', models.CharField(max_length=26, verbose_name='Серия и номер паспорта')),
                ('phone_number', models.CharField(max_length=26, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('num_home', models.CharField(max_length=5, verbose_name='Дом')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='Квартира')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('user_lead', models.ManyToManyField(blank=True, related_name='_consultant_user_lead_+', to='accounts.Consultant', verbose_name='Приглашённые консультантом')),
            ],
            options={
                'verbose_name': 'Консультант',
                'verbose_name_plural': 'Консультанты',
            },
        ),
        migrations.CreateModel(
            name='RefferalConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер консультанта')),
                ('url_to_personal_room', models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка в личный кабинет')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Зарегистрированный', 'Зарегистрированный'), ('Пустой', 'Пустой')], default='Новый', max_length=18, verbose_name='Статус регистрации')),
                ('refferal_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Реферальная ссылка')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('empty_middle_name', models.BooleanField(default=False, verbose_name='Нет отчества.')),
                ('birthday', models.DateTimeField(verbose_name='День рождения')),
                ('citizenship', models.BooleanField(default=False, verbose_name='Не гражданин РФ.')),
                ('passport_data', models.CharField(max_length=26, verbose_name='Серия и номер паспорта')),
                ('phone_number', models.CharField(max_length=26, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('num_home', models.CharField(max_length=5, verbose_name='Дом')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='Квартира')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('user_lead', models.ManyToManyField(blank=True, related_name='_refferalconsultant_user_lead_+', to='accounts.RefferalConsultant', verbose_name='Приглашённые консультантом')),
                ('user_lead_2', models.ManyToManyField(blank=True, related_name='consultants_of_refferal_consultant', to='accounts.Consultant', verbose_name='Приглашённые консультантом(Обычные)')),
                ('user_led', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultant', verbose_name='Пригласивший консультант')),
                ('user_led_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Consultant', verbose_name='Пригласивший консультант(Обычный)')),
            ],
            options={
                'verbose_name': 'Реферальный консультант',
                'verbose_name_plural': 'Реферальные консультанты',
            },
        ),
        migrations.CreateModel(
            name='RefferalConsultantTableRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер консультанта')),
                ('url_to_personal_room', models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка в личный кабинет')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Зарегистрированный', 'Зарегистрированный'), ('Пустой', 'Пустой')], default='Новый', max_length=18, verbose_name='Статус регистрации')),
                ('refferal_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Реферальная ссылка')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('empty_middle_name', models.BooleanField(default=False, verbose_name='Нет отчества.')),
                ('birthday', models.DateTimeField(verbose_name='День рождения')),
                ('citizenship', models.BooleanField(default=False, verbose_name='Не гражданин РФ.')),
                ('passport_data', models.CharField(max_length=26, verbose_name='Серия и номер паспорта')),
                ('phone_number', models.CharField(max_length=26, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('num_home', models.CharField(max_length=5, verbose_name='Дом')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='Квартира')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('user_lead', models.ManyToManyField(blank=True, related_name='_refferalconsultanttablerelations_user_lead_+', to='accounts.RefferalConsultantTableRelations', verbose_name='Приглашённые консультантом')),
                ('user_led', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultantTableRelations', verbose_name='Пригласивший консультант')),
            ],
            options={
                'verbose_name': 'Consultant',
            },
        ),
        migrations.CreateModel(
            name='RelatedConsultantTableRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=36, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('consultant_num', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер консультанта')),
                ('url_to_personal_room', models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка в личный кабинет')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Зарегистрированный', 'Зарегистрированный'), ('Пустой', 'Пустой')], default='Новый', max_length=18, verbose_name='Статус регистрации')),
                ('refferal_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Реферальная ссылка')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registered_date'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='RelatedConsultant',
            fields=[
                ('relatedconsultanttablerelations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.RelatedConsultantTableRelations')),
            ],
            options={
                'verbose_name': 'Сторонний консультант',
                'verbose_name_plural': 'Сторонний консультанты',
            },
            bases=('accounts.relatedconsultanttablerelations',),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='user_lead',
            field=models.ManyToManyField(blank=True, related_name='_relatedconsultanttablerelations_user_lead_+', to='accounts.RelatedConsultantTableRelations', verbose_name='Приглашённые консультантом'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='user_led',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RelatedConsultantTableRelations', verbose_name='Пригласивший консультант'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user_lead_1',
            field=models.ManyToManyField(blank=True, related_name='related_consultants_of_consultant', to='accounts.RelatedConsultantTableRelations', verbose_name='Приглашённые консультантом(Сторонние)'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user_lead_2',
            field=models.ManyToManyField(blank=True, related_name='refferal_consultants_of_consultant', to='accounts.RefferalConsultantTableRelations', verbose_name='Приглашённые консультантом(Реферальные)'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user_led',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Consultant', verbose_name='Пригласивший консультант'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user_led_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RelatedConsultantTableRelations', verbose_name='Пригласивший консультант(Сторонний)'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='user_led_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultantTableRelations', verbose_name='Пригласивший консультант(Реферальный)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_lead_1',
            field=models.ManyToManyField(blank=True, related_name='consultants_of_related_consultant', to='accounts.Consultant', verbose_name='Приглашённые консультантом(Обычные)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_lead_2',
            field=models.ManyToManyField(blank=True, related_name='refferal_consultants_of_related_consultant', to='accounts.RefferalConsultantTableRelations', verbose_name='Приглашённые консультантом(Реферальные)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_led_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Consultant', verbose_name='Пригласивший консультант(Обычный)'),
        ),
        migrations.AddField(
            model_name='relatedconsultant',
            name='user_led_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RefferalConsultantTableRelations', verbose_name='Пригласивший консультант(Реферальный)'),
        ),
        migrations.AddField(
            model_name='refferalconsultant',
            name='user_lead_1',
            field=models.ManyToManyField(blank=True, related_name='consultants_of_refferal_consultant', to='accounts.RelatedConsultant', verbose_name='Приглашённые консультантом(Сторонние)'),
        ),
        migrations.AddField(
            model_name='refferalconsultant',
            name='user_led_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.RelatedConsultant', verbose_name='Пригласивший консультант(Сторонний)'),
        ),
    ]
