# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180316_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferalconsultant',
            name='num_apartment',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=999, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='num_home',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='passport_data',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовый Индекс'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='num_apartment',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=999, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='num_home',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='passport_data',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовый Индекс'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_apartment',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=999, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_home',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_data',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовый Индекс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица'),
        ),
    ]
