# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171124_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='empty_middle_name',
            field=models.BooleanField(default=False, verbose_name='Нет отчества.'),
        ),
    ]
