# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180104_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedconsultant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
