# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_relatedconsultanttablerelations_empty_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferalconsultant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
