# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_relatedconsultanttablerelations_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedconsultanttablerelations',
            name='status',
        ),
    ]
