# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180314_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferalconsultant',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность консультанта'),
        ),
        migrations.AddField(
            model_name='refferalconsultant',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Пароль от аккаунта'),
        ),
        migrations.AddField(
            model_name='refferalconsultanttablerelations',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность консультанта'),
        ),
        migrations.AddField(
            model_name='refferalconsultanttablerelations',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Пароль от аккаунта'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность консультанта'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Пароль от аккаунта'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность консультанта'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Пароль от аккаунта'),
        ),
    ]
