# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180825_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferalconsultant',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город, Область'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город, Область'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город, Область'),
        ),
    ]
