# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171120_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='refferal_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='url_to_personal_room',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка в личный кабинет'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='refferal_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='refferalconsultant',
            name='url_to_personal_room',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка в личный кабинет'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='refferal_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='refferalconsultanttablerelations',
            name='url_to_personal_room',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка в личный кабинет'),
        ),
        migrations.AlterField(
            model_name='relatedconsultanttablerelations',
            name='refferal_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Реферальная ссылка'),
        ),
        migrations.AlterField(
            model_name='relatedconsultanttablerelations',
            name='url_to_personal_room',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка в личный кабинет'),
        ),
    ]
