# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('accounts', '0006_auto_20180927_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferalconsultant',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='refferalconsultant',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='refferalconsultanttablerelations',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='refferalconsultanttablerelations',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя пользователя'),
        ),
    ]
