# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181021_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferalconsultant',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AddField(
            model_name='refferalconsultanttablerelations',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AddField(
            model_name='relatedconsultanttablerelations',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Идентификатор пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Идентификатор пользователя'),
        ),
    ]
