# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='called_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 8, 47, 5, 374818, tzinfo=utc), verbose_name='Дата заказа обратного вызова'),
        ),
        migrations.AddField(
            model_name='callback',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Проконсультированный', 'Проконсультированный')], default='Новый', max_length=20, verbose_name='Статус обратного вызова'),
        ),
    ]
