# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171122_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='called_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заказа обратного вызова'),
        ),
    ]
