# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170426_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='action_2_10',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_2_11',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_2_12',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_2_9',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_10',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_11',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_12',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_3_9',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_10',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_11',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_12',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AddField(
            model_name='program',
            name='action_4_9',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_1_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_5',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_6',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_7',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_2_8',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_5',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_6',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_7',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_3_8',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_3',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_4',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_5',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнение'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_6',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_7',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='action_4_8',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Действие для выполнения'),
        ),
    ]
