# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171226_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='callback_name',
            field=models.CharField(max_length=160, verbose_name='ФИО'),
        ),
    ]
