# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170426_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('callback_phone', models.CharField(max_length=22, verbose_name='Телефон')),
                ('callback_message', models.TextField(max_length=250, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Обратный вызов',
                'verbose_name_plural': 'Обратные вызовы',
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_1',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Предложение 1 (под-заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_2',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Предложение (под-заголовок)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='p',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Параграф под заголовком'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заголовок'),
        ),
    ]
