# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171124_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_a', models.TextField(max_length=6000, verbose_name='Сообщение для зарегистрированного А')),
                ('registered_b', models.TextField(max_length=6000, verbose_name='Сообщение для зарегистрированного Б')),
                ('is_active', models.CharField(choices=[('Не активная группа', 'Не активна группа'), ('Активная группа', 'Активная группа')], default='Не активная группа', max_length=20, verbose_name='Активация')),
            ],
            options={
                'verbose_name': 'Email сообщение',
                'verbose_name_plural': 'Email сообщения',
            },
        ),
    ]
