# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180112_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='callback_message',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
    ]
