# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_emailmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMessage',
            new_name='EmailMessagesSetting',
        ),
    ]
