# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180715_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessagessetting',
            name='is_allow_sending_messages',
            field=models.BooleanField(default=True, verbose_name='Использовать информирование на почту?'),
        ),
    ]
