# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='map',
            field=models.TextField(blank=True, default='<iframe class="map__item"  src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8966.279574741344!2d37.726095!3d55.818067!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b53450cf0645b9%3A0x869f26e9d7ad24d3!2z0JjQstCw0L3RgtC10LXQstGB0LrQsNGPINGD0LsuLCAxM9C6MSwg0JzQvtGB0LrQstCwLCDQoNC-0YHRgdC40Y8sIDEwNzE1MA!5e0!3m2!1sru!2sru!4v1490693223242" frameborder="0" allowfullscreen></iframe>', help_text='Карта, которая отображается в контактах', max_length=2048, null=True, verbose_name='Окно с картой'),
        ),
        migrations.AlterField(
            model_name='sharespage',
            name='shares',
            field=models.ManyToManyField(blank=True, help_text='Акции, которые будут отображаться на странице "Акции".', related_name='shown_prices_sauna', to='shares.Share', verbose_name='Акции'),
        ),
    ]
