# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20171226_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpage',
            name='message',
            field=models.TextField(blank=True, default='Панель администрирования пополнилась новым консультаном!', help_text='<div class="variablesHint">Доступные переменные:<br/><br/><span class="variable">{{first_name}}</span> &mdash; <span class="helpText">Иван</span><br/><span class="variable">{{last_name}}</span> &mdash; <span class="helpText">Иванович</span><br/><span class="variable">{{middle_name}}</span> &mdash; <span class="helpText">Иванов</span><br/><span class="variable">{{full_name}}</span> &mdash; <span class="helpText">Иван Иванович</span><br/><span class="variable">{{status}}</span> &mdash; <span class="helpText">Зарегистрированный "А"/Новый</span><br/><span class="variable">{{site}}</span> &mdash; <span class="helpText">cosmeticsyou.ru.</span><br/><div>', max_length=1000, null=True, verbose_name='Опциональное сообщение'),
        ),
        migrations.AlterField(
            model_name='registrationpage',
            name='phone_from',
            field=models.CharField(blank=True, default='+79651581481', max_length=20, null=True, verbose_name='Телефон для отправки сообщений'),
        ),
    ]
