# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180118_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpage',
            name='account_sid',
            field=models.CharField(blank=True, default='', help_text='Account Sid из аккаунта TwilioAPI', max_length=350, null=True, verbose_name='Account Sid'),
        ),
        migrations.AddField(
            model_name='registrationpage',
            name='auth_token',
            field=models.CharField(blank=True, default='', help_text='Auth Token из аккаунта TwilioAPI', max_length=350, null=True, verbose_name='Auth Token'),
        ),
        migrations.AlterField(
            model_name='registrationpage',
            name='phone_from',
            field=models.CharField(blank=True, default='+17609068017', max_length=20, null=True, verbose_name='Телефон для отправки сообщений'),
        ),
        migrations.AlterField(
            model_name='registrationpage',
            name='phones_to',
            field=models.TextField(blank=True, default='+79859051251', help_text='Указывайте телефоны через запятую +7000999222,+7222111333', max_length=1000, null=True, verbose_name='Телефоны для отправления сообщений'),
        ),
    ]
