# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('fist_name', models.CharField(max_length=24, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='Отчество')),
                ('birthday', models.DateTimeField(verbose_name='День рождения')),
                ('passport_data', models.CharField(max_length=16, verbose_name='Серия и номер паспорта')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=40, null=True, verbose_name='Область')),
                ('street', models.CharField(max_length=32, verbose_name='Улица')),
                ('num_home', models.DecimalField(decimal_places=1, max_digits=150, verbose_name='Дом')),
                ('num_apartment', models.DecimalField(decimal_places=1, max_digits=999, verbose_name='Квартира')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
        ),
    ]
