# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='Не гражданин РФ.'),
        ),
        migrations.AddField(
            model_name='user',
            name='empty_middle_name',
            field=models.BooleanField(default=False, verbose_name='Без отчества.'),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
