# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170405_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_home',
            field=models.CharField(max_length=5, verbose_name=b'\xd0\x94\xd0\xbe\xd0\xbc'),
        ),
    ]
