# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170406_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(None, 'Новый'), (None, 'Зарегистрированный'), (None, 'Пустой')], default=(None, 'Новый'), max_length=2, verbose_name='Статус регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.BooleanField(default=False, verbose_name='Не гражданин РФ.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='empty_middle_name',
            field=models.BooleanField(default=False, verbose_name='Нет отчества.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=36, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_apartment',
            field=models.DecimalField(decimal_places=1, max_digits=999, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_home',
            field=models.CharField(max_length=5, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_data',
            field=models.CharField(max_length=26, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=26, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
    ]
