# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170407_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(None, 'Новый'), (None, 'Зарегистрированный'), (None, 'Пустой')], default='Новый', max_length=2, verbose_name='Статус регистрации'),
        ),
    ]
