# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170407_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('REG', 'Зарегистрированный'), ('EMP', 'Пустой')], default='NEW', max_length=3, verbose_name='Статус регистрации'),
        ),
    ]
