# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170407_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-registered_date'], 'verbose_name': 'Консультанты'},
        ),
        migrations.AddField(
            model_name='user',
            name='consultant_num',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер консультанта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Зарегистрированный', 'Зарегистрированный'), ('Пустой', 'Пустой')], default='Новый', max_length=18, verbose_name='Статус регистрации'),
        ),
    ]
