# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import pages.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20171225_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='slug',
            field=models.SlugField(blank=True, help_text='К примеру, "new-share-for_2018"', max_length=150, null=True, validators=[pages.validators.validate_slug_field], verbose_name='Название ссылки к странице акции'),
        ),
    ]
