# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_auto_20180104_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='announce',
            field=models.TextField(blank=True, max_length=560, null=True, verbose_name='Анонс акции'),
        ),
        migrations.AddField(
            model_name='share',
            name='page_title',
            field=models.CharField(blank=True, help_text='Название страницы во вкладке', max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='share',
            name='additional_text',
            field=models.TextField(blank=True, max_length=16384, null=True, verbose_name='Контент'),
        ),
    ]
