# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_auto_20180118_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='img',
            field=models.FileField(blank=True, help_text='Путь к изображению /media/shares/ на сервере.', null=True, upload_to='shares/', verbose_name='Главное Изображение'),
        ),
    ]
