# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import pages.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('shares', '0006_auto_20180119_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page_title', models.CharField(blank=True, help_text='Название страницы во вкладке', max_length=100, null=True, verbose_name='Заголовок')),
                ('meta', models.TextField(blank=True, max_length=300, null=True, verbose_name='META-описание страницы')),
                ('title', models.CharField(max_length=250, verbose_name='Название новости')),
                ('slug', models.SlugField(blank=True, help_text='К примеру, "new-share-for_2018"', max_length=150, null=True, validators=[pages.validators.validate_slug_field], verbose_name='Название ссылки к странице акции')),
                ('content', models.TextField(blank=True, max_length=16384, null=True, verbose_name='Контент')),
                ('announce', models.TextField(blank=True, max_length=560, null=True, verbose_name='Анонс')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Отобразить новость?')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='Идентификатор новости')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album', verbose_name='Альбом с изображениями')),
                ('preview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.AlbumImage', verbose_name='Главное Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'consultant_news',
                'ordering': ['-created_at'],
            },
        ),
    ]
