# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20170402_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='text_1_2_1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_1_2_2',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_1_3_1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_1_3_2',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_1_4_1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_1_4_2',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_1_5_1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_1_5_2',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_2_2_1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_2_2_2',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_2_4_1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_2_4_2',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_2_5_1',
        ),
        migrations.RemoveField(
            model_name='share',
            name='text_2_5_2',
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_2_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_2_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_3_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_3_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_4_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_4_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_5_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_1_5_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_2_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_2_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_3_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_3_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_4_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_4_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_5_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='share',
            name='p_2_5_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='conditions_h2_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Условия акции'),
        ),
        migrations.AlterField(
            model_name='share',
            name='conditions_h2_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Условия акции'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_1_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_1_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображние'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_1_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_1_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_2_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_2_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_2_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_2_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_3_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_3_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_3_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_3_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_4_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_4_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_4_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_4_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_5_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_5_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_5_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_1_5_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_1_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_1_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_1_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_1_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_2_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_2_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_2_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_2_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_3_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_3_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_3_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_3_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_4_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_4_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_4_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_4_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_5_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_5_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_5_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_2_5_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s1_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s1_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s2_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s2_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s3_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s3_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s4_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s4_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s5_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='img_s5_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение набора'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_1_1',
            field=models.TextField(blank=True, null=True, verbose_name='Первый пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_1_2',
            field=models.TextField(blank=True, null=True, verbose_name='Второй пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_1_3',
            field=models.TextField(blank=True, null=True, verbose_name='Третий пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_1_4',
            field=models.TextField(blank=True, null=True, verbose_name='Четвёртый пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_1_5',
            field=models.TextField(blank=True, null=True, verbose_name='Пятый пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_2_1',
            field=models.TextField(blank=True, null=True, verbose_name='Первый пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_2_2',
            field=models.TextField(blank=True, null=True, verbose_name='Второй пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_2_3',
            field=models.TextField(blank=True, null=True, verbose_name='Третий пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_2_4',
            field=models.TextField(blank=True, null=True, verbose_name='Четвёртый пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_2_5',
            field=models.TextField(blank=True, null=True, verbose_name='Пятый пункт условий'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s1_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s1_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s1_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s1_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s2_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s2_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s2_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s2_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s3_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s3_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s3_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s3_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s4_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s4_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s4_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s4_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s5_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s5_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s5_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='item_s5_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вещь в наборе'),
        ),
        migrations.AlterField(
            model_name='share',
            name='p_1_1_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='p_1_1_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='p_2_1_1',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='p_2_1_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='set_h3_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Набор'),
        ),
        migrations.AlterField(
            model_name='share',
            name='set_h3_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Набор'),
        ),
        migrations.AlterField(
            model_name='share',
            name='set_h3_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Набор'),
        ),
        migrations.AlterField(
            model_name='share',
            name='set_h3_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Набор'),
        ),
        migrations.AlterField(
            model_name='share',
            name='set_h3_5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Набор'),
        ),
        migrations.AlterField(
            model_name='share',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='text_3',
            field=models.TextField(blank=True, null=True, verbose_name='Параграф'),
        ),
        migrations.AlterField(
            model_name='share',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название акции'),
        ),
    ]
